test 3

diff --git a/.github/workflows/deployment.yml b/.github/workflows/deployment.yml
--- a/.github/workflows/deployment.yml
+++ b/.github/workflows/deployment.yml
@@ -19,10 +19,20 @@ jobs:
   dynamicBranch:
     runs-on: ubuntu-latest
     outputs:
-      develop: develop
-      master: production
-      staging: staging
-
+      pr-number: ${{ steps.dyn-branch.outputs.env_name }}
+    steps:
+      - name: Set dynamic branch name
+        id: dyn-branch
+        run: |
+          if [ "${{ github.ref_name }}" == "develop" ]; then
+            echo "env_name=develop" >> $GITHUB_OUTPUT
+          elif [ "${{ github.ref_name }}" == "master" ]; then
+            echo "env_name=production" >> $GITHUB_OUTPUT
+          elif [ "${{ github.ref_name }}" == "develop" ]; then
+            echo "env_name=develop" >> $GITHUB_OUTPUT
+          else
+            echo "ERROR: The environment is not defined"; exit 1;
+          fi
   Deployment:
     name: Deploy to ${{github.ref_name}}
     needs: [dynamicBranch]
@@ -30,7 +40,7 @@ jobs:
     runs-on: ubuntu-latest
 
     environment:
-      name: ${{ needs.dynamicBranch[github.ref_name] }}
+      name: ${{ needs.dynamicBranch.outputs.env_name }}
 
     strategy:
       matrix:
